### PR TITLE
come on give in

### PR DESCRIPTION
**Pull request by sarimwaniR**

### CODE REVIEW

**Comment by snappiee** [comment]
my code come on you can advertise your free hosting by another way

**Comment by sarimwaniR** [comment]
BRUH

**Comment by sarimwaniR** [comment]
I WANT TO HELP

**Comment by sarimwaniR** [comment]
I am trying a find a software similar to replit

**Comment by sarimwaniR** [comment]
hence it is classified as a vm

**Comment by kyan0045** [comment]
> I am trying a find a software similar to replit

Use any pterodactyl based free NodeJS hosting...

**Pull request closed without merging**
